name: surah_name_ayah_image
description: "Ayah Image Generator."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  http: ^1.2.1
  provider: ^6.1.2
  pasteboard: ^0.2.0
  url_launcher: ^6.2.5
  widgets_to_image: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: SurahNamesFont
      fonts:
        - asset: fonts/QCF_BSML.ttf
